### ISSUE TITLE
Empty screen

### ISSUE THREAD

**Issue by narbs** [danchoi/vitunes#1]
Is there a way to troubleshoot an empty screen when starting vitunes? Installed 0.3.8 but all I can see is:

Welcome to ViTunes                                                              

Press ? for help

Is there a reason for not being able to connect to itunes from within vitunes?

**Comment by danchoi** [comment]
The screen is waiting for you to press a command key sequence. Did you try pressing ? to see the command list?

**Comment by narbs** [comment]
Ok was expecting to see the full list of songs there rather than searching... like the default behaviour in iTunes. Thanks

**Comment by danchoi** [comment]
Yes, the default behavior is different. Loading the full list of songs on the start screen in ViTunes would add a second or two to start up time and I wanted to keep it lean and economical.
