### ISSUE TITLE
Can't search or choose a new song on OS X 10.10

### ISSUE THREAD

**Issue by tyilo** [danchoi/vitunes#17]
Playing/pausing, displaying current track and changing volume works.

I'm getting the following error in the console:

```
02/07/15 00:46:34,074 vitunes-tool-objc[64639]: AppleEvents: Send port for process has no send right, port=( port:14619/0x391b rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
```

I'm using OS X 10.10.3 and iTunes 12.2.

**Comment by danchoi** [comment]
Sorry -- I have no time right now to maintain this project. Any volunteers?

**Comment by tyilo** [comment]
Just recompiling `vitunes-tool-objc` in Xcode fixed it for me.
